import {Model, ModelOrigin} from '../utils/types';
import {chatTemplates, defaultCompletionParams} from '../utils/chat';
import {Platform} from 'react-native';

export const MODEL_LIST_VERSION = 9;

const iosOnlyModels: Model[] = [];

const androidOnlyModels: Model[] = [
  // --- Llama ---
  {
    id: 'default-llama-3.2-1b-instruct-q4_0_4_4.gguf',
    author: 'bartowski',
    name: 'llama-3.2-1b-instruct (Q4_0_4_4)',
    type: 'Llama',
    size: 770928768,
    params: 1235814432,
    isDownloaded: false,
    downloadUrl:
      'https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_0_4_4.gguf?download=true',
    hfUrl: 'https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF',
    progress: 0,
    filename: 'default-llama-3.2-1b-instruct-q4_0_4_4.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.llama32},
    chatTemplate: chatTemplates.llama32,
    defaultCompletionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.5,
      stop: ['<|im_end|>'],
    },
    completionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.5,
      stop: ['<|im_end|>'],
    },
  },
  {
    id: 'default-llama-3.2-1b-instruct-q4_0_4_8.gguf',
    author: 'bartowski',
    name: 'llama-3.2-1b-instruct (Q4_0_4_8)',
    type: 'Llama',
    size: 770928768,
    params: 1235814432,
    isDownloaded: false,
    downloadUrl:
      'https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_0_4_8.gguf?download=true',
    hfUrl: 'https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF',
    progress: 0,
    filename: 'default-llama-3.2-1b-instruct-q4_0_4_8.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.llama32},
    chatTemplate: chatTemplates.llama32,
    defaultCompletionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.5,
      stop: ['<|im_end|>'],
    },
    completionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.5,
      stop: ['<|im_end|>'],
    },
  },
  {
    id: 'default-llama-3.2-1b-instruct-q4_0_8_8.gguf',
    author: 'bartowski',
    name: 'llama-3.2-1b-instruct (Q4_0_8_8)',
    type: 'Llama',
    size: 770928768,
    params: 1235814432,
    isDownloaded: false,
    downloadUrl:
      'https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_0_8_8.gguf?download=true',
    hfUrl: 'https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF',
    progress: 0,
    filename: 'default-llama-3.2-1b-instruct-q4_0_8_8.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.llama32},
    chatTemplate: chatTemplates.llama32,
    defaultCompletionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.5,
      stop: ['<|im_end|>'],
    },
    completionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.5,
      stop: ['<|im_end|>'],
    },
  },
  // --- SmolLM ---
  {
    id: 'default-bartowski/SmolLM2-1.7B-Instruct-Q4_0_4_4.gguf',
    author: 'bartowski',
    name: 'SmolLM2-1.7B-Instruct (Q4_0_4_4)',
    type: 'SmolLM',
    size: 990729184,
    params: 1711376384,
    isDownloaded: false,
    downloadUrl:
      'https://huggingface.co/bartowski/SmolLM2-1.7B-Instruct-GGUF/resolve/main/SmolLM2-1.7B-Instruct-Q4_0_4_4.gguf?download=true',
    hfUrl: 'https://huggingface.co/bartowski/SmolLM2-1.7B-Instruct-GGUF',
    progress: 0,
    filename: 'default-SmolLM2-1.7B-Instruct-Q4_0_4_4.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: chatTemplates.smolLM,
    chatTemplate: chatTemplates.smolLM,
    defaultCompletionSettings: {
      ...defaultCompletionParams,
      n_predict: 1000,
      temperature: 0.7,
      stop: ['<|endoftext|>', '<|im_end|>'],
    },
    completionSettings: {
      ...defaultCompletionParams,
      n_predict: 1000,
      temperature: 0.7,
      stop: ['<|endoftext|>', '<|im_end|>'],
    },
  },
];

const crossPlatformModels: Model[] = [
  // -------- Gemma --------
  {
    id: 'google/gemma-2-2b-it-GGUF',
    author: 'bartowski',
    name: 'gemma-2-2b-it-GGUF (Q6_K)',
    type: 'Gemma',
    size: 2151393120,
    params: 2614341888,
    isDownloaded: false,
    downloadUrl:
      'https://huggingface.co/bartowski/gemma-2-2b-it-GGUF/resolve/main/gemma-2-2b-it-Q6_K.gguf?download=true',
    hfUrl: 'https://huggingface.co/bartowski/gemma-2-2b-it-GGUF',
    progress: 0,
    filename: 'gemma-2-2b-it-Q6_K.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.gemmaIt},
    chatTemplate: chatTemplates.gemmaIt,
    defaultCompletionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.0,
      penalty_repeat: 1.0,
      stop: ['<end_of_turn>'],
    },
    completionSettings: {
      // https://huggingface.co/google/gemma-7b-it/discussions/38#65d7b14adb51f7c160769fa1
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.0,
      penalty_repeat: 1.0,
      stop: ['<end_of_turn>'],
    },
  },
  {
    id: 'google/gemma-1.1-2b-it-GGUF',
    author: 'bartowski',
    name: 'gemma-1.1-2b-it-GGUF (Q6_K)',
    type: 'Gemma',
    size: 2062124768,
    params: 2506172416,
    isDownloaded: false,
    downloadUrl:
      'https://huggingface.co/bartowski/gemma-1.1-2b-it-GGUF/resolve/main/gemma-1.1-2b-it-Q6_K.gguf?download=true',
    hfUrl: 'https://huggingface.co/bartowski/gemma-1.1-2b-it-GGUF',
    progress: 0,
    filename: 'gemma-1.1-2b-it-Q6_K.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.gemmaIt},
    chatTemplate: chatTemplates.gemmaIt,
    defaultCompletionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.0,
      penalty_repeat: 1.0,
      stop: ['<end_of_turn>'],
    },
    completionSettings: {
      // https://huggingface.co/google/gemma-7b-it/discussions/38#65d7b14adb51f7c160769fa1
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.0,
      penalty_repeat: 1.0,
      stop: ['<end_of_turn>'],
    },
  },
  {
    id: 'Gemmasutra-Mini-2B-v1-Q6_K.gguf',
    author: 'TheDrummer',
    name: 'Gemmasutra-Mini-2B-v1-GGUF (Q6_K)',
    type: 'Gemma',
    size: 2151393152,
    params: 2614341888,
    isDownloaded: false,
    downloadUrl:
      'https://huggingface.co/TheDrummer/Gemmasutra-Mini-2B-v1-GGUF/resolve/main/Gemmasutra-Mini-2B-v1-Q6_K.gguf?download=true',
    hfUrl: 'https://huggingface.co/TheDrummer/Gemmasutra-Mini-2B-v1-GGUF',
    progress: 0,
    filename: 'Gemmasutra-Mini-2B-v1-Q6_K.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.gemmasutra},
    chatTemplate: chatTemplates.gemmasutra,
    defaultCompletionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.7,
      penalty_repeat: 1.0,
      stop: ['<end_of_turn>'],
    },
    completionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.7,
      penalty_repeat: 1.0,
      stop: ['<end_of_turn>'],
    },
  },
  // -------- Danube --------
  {
    id: 'h2o-danube3-4b-chat-Q4_K_M.gguf',
    author: 'h2oai',
    name: 'H2O.ai Danube 3 (Q4_K_M)',
    type: 'Danube',
    size: 2394648960,
    params: 3961839360,
    isDownloaded: false,
    downloadUrl:
      'https://huggingface.co/h2oai/h2o-danube3-4b-chat-GGUF/resolve/main/h2o-danube3-4b-chat-Q4_K_M.gguf?download=true',
    hfUrl: 'https://huggingface.co/h2oai/h2o-danube3-4b-chat-GGUF',
    progress: 0,
    filename: 'h2o-danube3-4b-chat-Q4_K_M.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {
      ...chatTemplates.danube3,
    },
    chatTemplate: {
      ...chatTemplates.danube3,
    },
    defaultCompletionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.1,
      penalty_repeat: 1.075,
    },
    completionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.1,
      penalty_repeat: 1.075,
    },
  },
  {
    id: 'h2o-danube2-1.8b-chat-Q6_K.gguf',
    author: 'h2oai',
    name: 'H2O.ai Danube 2 (Q6_K)',
    type: 'Danube',
    size: 1503287456,
    params: 1831201280,
    isDownloaded: false,
    downloadUrl:
      'https://huggingface.co/h2oai/h2o-danube2-1.8b-chat-GGUF/resolve/main/h2o-danube2-1.8b-chat-Q6_K.gguf?download=true',
    hfUrl: 'https://huggingface.co/h2oai/h2o-danube2-1.8b-chat-GGUF',
    progress: 0,
    filename: 'h2o-danube2-1.8b-chat-Q6_K.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {
      ...chatTemplates.danube2,
    },
    chatTemplate: {
      ...chatTemplates.danube2,
    },
    defaultCompletionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.1,
      penalty_repeat: 1.075,
    },
    completionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.1,
      penalty_repeat: 1.075,
    },
  },
  {
    id: 'h2o-danube2-1.8b-chat-Q5_K_S.gguf',
    author: 'h2oai',
    name: 'H2O.ai Danube 2 (Q5_K_S)',
    type: 'Danube',
    size: 1270977696,
    params: 1831201280,
    isDownloaded: false,
    downloadUrl:
      'https://huggingface.co/h2oai/h2o-danube2-1.8b-chat-GGUF/resolve/main/h2o-danube2-1.8b-chat-Q5_K_S.gguf?download=true',
    hfUrl: 'https://huggingface.co/h2oai/h2o-danube2-1.8b-chat-GGUF',
    progress: 0,
    filename: 'h2o-danube2-1.8b-chat-Q5_K_S.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {
      ...chatTemplates.danube2,
    },
    chatTemplate: {
      ...chatTemplates.danube2,
    },
    defaultCompletionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.5,
      penalty_repeat: 1.075,
    },
    completionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.5,
      penalty_repeat: 1.075,
    },
  },
  // -------- Phi --------
  {
    id: 'Phi-3.5-mini-instruct.Q4_K_M.gguf',
    author: 'QuantFactory',
    name: 'Phi-3.5 mini 4k instruct (Q4_K_M)',
    type: 'Phi',
    size: 2394648960,
    params: 3821079648,
    isDownloaded: false,
    downloadUrl:
      'https://huggingface.co/QuantFactory/Phi-3.5-mini-instruct-GGUF/resolve/main/Phi-3.5-mini-instruct.Q4_K_M.gguf?download=true',
    hfUrl: 'https://huggingface.co/QuantFactory/Phi-3.5-mini-instruct-GGUF',
    progress: 0,
    filename: 'Phi-3.5-mini-instruct.Q4_K_M.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.phi3},
    chatTemplate: chatTemplates.phi3,
    defaultCompletionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.1,
      stop: ['<|end|>'],
    },
    completionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.1,
      stop: ['<|end|>'],
    },
  },
  {
    id: 'Phi-3-mini-4k-instruct-q4.gguf',
    author: 'bartowski',
    name: 'Phi-3.1 mini 4k instruct (Q4_K_M)',
    type: 'Phi',
    size: 2394648960,
    params: 3821079552,
    isDownloaded: false,
    downloadUrl:
      'https://huggingface.co/bartowski/Phi-3.1-mini-4k-instruct-GGUF/resolve/main/Phi-3.1-mini-4k-instruct-Q4_K_M.gguf?download=true',
    hfUrl: 'https://huggingface.co/bartowski/Phi-3.1-mini-4k-instruct-GGUF',
    progress: 0,
    filename: 'Phi-3.1-mini-4k-instruct-Q4_K_M.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.phi3},
    chatTemplate: chatTemplates.phi3,
    defaultCompletionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.1,
      stop: ['<|end|>'],
    },
    completionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.1,
      stop: ['<|end|>'],
    },
  },
  // -------- Qwen --------
  {
    id: 'qwen2-1_5b-instruct-q8_0.gguf',
    author: 'Qwen',
    name: 'Qwen2-1.5B-Instruct (Q8_0)',
    type: 'Qwen',
    size: 1652387840,
    params: 1543714304,
    isDownloaded: false,
    downloadUrl:
      'https://huggingface.co/Qwen/Qwen2-1.5B-Instruct-GGUF/resolve/main/qwen2-1_5b-instruct-q8_0.gguf?download=true',
    hfUrl: 'https://huggingface.co/Qwen/Qwen2-1.5B-Instruct-GGUF',
    progress: 0,
    filename: 'qwen2-1_5b-instruct-q8_0.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.qwen2},
    chatTemplate: chatTemplates.qwen2,
    defaultCompletionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.5,
      stop: ['<|im_end|>'],
    },
    completionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.5,
      stop: ['<|im_end|>'],
    },
  },
  {
    id: 'qwen2.5-1.5b-instruct-q8_0.gguf',
    author: 'Qwen',
    name: 'Qwen2.5-1.5B-Instruct (Q8_0)',
    type: 'Qwen',
    size: 1892387840,
    params: 1777088000,
    isDownloaded: false,
    downloadUrl:
      'https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/qwen2.5-1.5b-instruct-q8_0.gguf?download=true',
    hfUrl: 'https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF',
    progress: 0,
    filename: 'qwen2.5-1.5b-instruct-q8_0.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.qwen25},
    chatTemplate: chatTemplates.qwen25,
    defaultCompletionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.5,
      stop: ['<|im_end|>'],
    },
    completionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.5,
      stop: ['<|im_end|>'],
    },
  },
  {
    id: 'qwen2.5-3b-instruct-q5_0.gguf',
    author: 'Qwen',
    name: 'Qwen2.5-3B-Instruct (Q5_0)',
    type: 'Qwen',
    size: 2384387840,
    params: 3397103616,
    isDownloaded: false,
    downloadUrl:
      'https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF/resolve/main/qwen2.5-3b-instruct-q5_0.gguf?download=true',
    hfUrl: 'https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF',
    progress: 0,
    filename: 'qwen2.5-3b-instruct-q5_0.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.qwen25},
    chatTemplate: chatTemplates.qwen25,
    defaultCompletionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.5,
      stop: ['<|im_end|>'],
    },
    completionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.5,
      stop: ['<|im_end|>'],
    },
  },
  // -------- Llama --------
  {
    id: 'default-llama-3.2-1b-instruct-q8_0.gguf',
    author: 'hugging-quants',
    name: 'llama-3.2-1b-instruct (Q8_0)',
    type: 'Llama',
    size: 1321079200,
    params: 1235814432,
    isDownloaded: false,
    downloadUrl:
      'https://huggingface.co/hugging-quants/Llama-3.2-1B-Instruct-Q8_0-GGUF/resolve/main/llama-3.2-1b-instruct-q8_0.gguf?download=true',
    hfUrl:
      'https://huggingface.co/hugging-quants/Llama-3.2-1B-Instruct-Q8_0-GGUF',
    progress: 0,
    filename: 'default-llama-3.2-1b-instruct-q8_0.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.llama32},
    chatTemplate: chatTemplates.llama32,
    defaultCompletionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.5,
      stop: ['<|eot_id|>'],
    },
    completionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.5,
      stop: ['<|eot_id|>'],
    },
  },
  {
    id: 'llama-3.2-3b-instruct-q4_k_m.gguf',
    author: 'hugging-quants',
    name: 'llama-3.2-3b-instruct (Q4_K)',
    type: 'Llama',
    size: 2019373920,
    params: 3212749888,
    isDownloaded: false,
    downloadUrl:
      'https://huggingface.co/hugging-quants/Llama-3.2-3B-Instruct-Q4_K_M-GGUF/resolve/main/llama-3.2-3b-instruct-q4_k_m.gguf?download=true',
    hfUrl:
      'https://huggingface.co/hugging-quants/Llama-3.2-3B-Instruct-Q4_K_M-GGUF',
    progress: 0,
    filename: 'llama-3.2-3b-instruct-q4_k_m.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.llama32},
    chatTemplate: chatTemplates.llama32,
    defaultCompletionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.5,
      stop: ['<|eot_id|>'],
    },
    completionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.5,
      stop: ['<|eot_id|>'],
    },
  },
  {
    id: 'Llama-3.2-3B-Instruct-Q6_K.gguf',
    author: 'bartowski',
    name: 'Llama-3.2-3B-Instruct (Q6_K)',
    type: 'Llama',
    size: 2643853856,
    params: 3212749888,
    isDownloaded: false,
    downloadUrl:
      'https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q6_K.gguf?download=true',
    hfUrl: 'https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF',
    progress: 0,
    filename: 'Llama-3.2-3B-Instruct-Q6_K.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.llama32},
    chatTemplate: chatTemplates.llama32,
    defaultCompletionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.5,
      stop: ['<|eot_id|>'],
    },
    completionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.5,
      stop: ['<|eot_id|>'],
    },
  },
  // TODO: Add memory check for this model
  {
    id: 'llama-3.2-3b-instruct-q8_0.gguf',
    author: 'hugging-quants',
    name: 'llama-3.2-3b-instruct q8_k',
    type: 'Llama',
    size: 3421895520,
    params: 3212749888,
    isDownloaded: false,
    downloadUrl:
      'https://huggingface.co/hugging-quants/Llama-3.2-3B-Instruct-Q8_0-GGUF/resolve/main/llama-3.2-3b-instruct-q8_0.gguf?download=true',
    hfUrl:
      'https://huggingface.co/hugging-quants/Llama-3.2-3B-Instruct-Q8_0-GGUF',
    progress: 0,
    filename: 'llama-3.2-3b-instruct-q8_0.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: {...chatTemplates.llama32},
    chatTemplate: chatTemplates.llama32,
    defaultCompletionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.5,
      stop: ['<|eot_id|>'],
    },
    completionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.5,
      stop: ['<|eot_id|>'],
    },
  },
  // -------- SmolLM --------
  {
    id: 'default-bartowski/SmolLM2-1.7B-Instruct-Q8_0.gguf',
    author: 'bartowski',
    name: 'SmolLM2-1.7B-Instruct (Q8_0)',
    type: 'SmolLM',
    size: 1820414944,
    params: 1711376384,
    isDownloaded: false,
    downloadUrl:
      'https://huggingface.co/bartowski/SmolLM2-1.7B-Instruct-GGUF/resolve/main/SmolLM2-1.7B-Instruct-Q8_0.gguf?download=true',
    hfUrl: 'https://huggingface.co/bartowski/SmolLM2-1.7B-Instruct-GGUF',
    progress: 0,
    filename: 'default-SmolLM2-1.7B-Instruct-Q8_0.gguf',
    isLocal: false,
    origin: ModelOrigin.PRESET,
    defaultChatTemplate: chatTemplates.smolLM,
    chatTemplate: chatTemplates.smolLM,
    defaultCompletionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.7,
      stop: ['<|endoftext|>', '<|im_end|>'],
    },
    completionSettings: {
      ...defaultCompletionParams,
      n_predict: 500,
      temperature: 0.7,
      stop: ['<|endoftext|>', '<|im_end|>'],
    },
  },
];

export const defaultModels =
  Platform.OS === 'android'
    ? [...androidOnlyModels, ...crossPlatformModels]
    : [...iosOnlyModels, ...crossPlatformModels];
